# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fiches.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apothicaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medecine', fiches.functions.IntegerRangeField(default=0)),
                ('chirurgie', fiches.functions.IntegerRangeField(default=0)),
                ('poison', fiches.functions.IntegerRangeField(default=0)),
                ('guerisseur', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
                ('alchimie', fiches.functions.IntegerRangeField(default=0)),
                ('equitation', fiches.functions.IntegerRangeField(default=0)),
                ('maitr_scalpel', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
                ('lancer_fioles', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
                ('maitr_guerisseur', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
                ('enfumeur', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Armure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effet', models.CharField(default=b'Aucun', max_length=100)),
                ('autres_effets', models.CharField(default=b'Aucun', max_length=100)),
                ('effet_ig', models.CharField(default=b'Aucun', max_length=100)),
                ('force', fiches.functions.IntegerRangeField(default=0)),
                ('intell', fiches.functions.IntegerRangeField(default=0)),
                ('agi', fiches.functions.IntegerRangeField(default=0)),
                ('membre', models.SmallIntegerField(choices=[(1, b'Main principale'), (2, b'Autre main'), (3, b'T\xc3\xaate'), (4, b'Epaules'), (5, b'Torse'), (6, b'Mains'), (7, b'Taille'), (8, b'Jambes'), (9, b'Pieds'), (10, b'Dos'), (11, b'Cou'), (12, b'Doigt'), (13, b'Poignets'), (14, b'Divers')], default=5)),
                ('armure', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['membre'],
                'verbose_name_plural': 'armures',
                'default_related_name': 'armure',
                'verbose_name': 'armure',
                'permissions': (('armure_ok', 'Peut faire des armures'),),
            },
        ),
        migrations.CreateModel(
            name='Avant_garde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[(b'h', b'Homme'), (b'f', b'Femme')], default=b'Homme', max_length=1)),
                ('jour_de_naissance', fiches.functions.IntegerRangeField(default=b'1')),
                ('mois_de_naissance', fiches.functions.IntegerRangeField(default=b'1')),
                ('annee_de_naissance', fiches.functions.IntegerRangeField(default=b'0')),
                ('ville_de_naissance', models.CharField(default=b'Inconnue', max_length=50)),
                ('race', models.CharField(choices=[(b'n', b'Nain'), (b'e', b'Haut-elfe'), (b'h', b'Humain')], default=b'Humain', max_length=1)),
                ('ex_prof', models.SmallIntegerField(choices=[(1, b'Forgeron'), (2, b'Chasseur'), (3, b'Cuisinier'), (4, b'Tavernier'), (5, b"Facteur d'arc"), (6, b'Tanneur'), (7, b'Architecte'), (8, b'Eb\xc3\xa9niste'), (9, b'Autre m\xc3\xa9tier')], default=9)),
                ('autre_metier', models.CharField(default=b'Aucun', max_length=30)),
                ('grade_rp', models.SmallIntegerField(choices=[(1, b'Soldat'), (2, b'Caporal'), (3, b'Sergent'), (4, b'Lieutenant'), (5, b'Capitaine')], default=1)),
                ('cap_combat', fiches.functions.IntegerRangeField(default=1)),
                ('cap_tir', fiches.functions.IntegerRangeField(default=1)),
                ('force', fiches.functions.IntegerRangeField(default=1)),
                ('endu', fiches.functions.IntegerRangeField(default=1)),
                ('perce', fiches.functions.IntegerRangeField(default=1)),
                ('agi', fiches.functions.IntegerRangeField(default=1)),
                ('intell', fiches.functions.IntegerRangeField(default=1)),
                ('charisme', fiches.functions.IntegerRangeField(default=1)),
                ('force_men', fiches.functions.IntegerRangeField(default=1)),
                ('pv', models.SmallIntegerField(default=11)),
                ('ps', models.SmallIntegerField(default=0)),
                ('pf', models.SmallIntegerField(default=0)),
                ('niveau', models.SmallIntegerField(default=1)),
                ('xp', models.SmallIntegerField(default=0)),
                ('blessures', models.CharField(blank=True, default=b'Sans', max_length=800, null=True)),
                ('troubles_ment', models.CharField(blank=True, default=b'Sans', max_length=800, null=True)),
                ('image', models.ImageField(default=b'images/site/no-image.png', upload_to=b'images/persos')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', fiches.functions.IntegerRangeField(default=1)),
            ],
            options={
                'ordering': ['nombre', 'objet'],
                'verbose_name_plural': 'cases',
                'default_related_name': 'case',
                'verbose_name': 'case',
                'permissions': (('case_ok', 'Peut faire des cases'),),
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=b'Equipement', max_length=50)),
                ('objets', models.ManyToManyField(related_name='equipement', to='fiches.Armure')),
            ],
            options={
                'permissions': (('equipement_ok', 'Peut faire des \xe9quipements'),),
                'verbose_name': 'equipement',
                'verbose_name_plural': 'equipements',
                'default_related_name': 'equipement',
            },
        ),
        migrations.CreateModel(
            name='Fantassin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intim', fiches.functions.IntegerRangeField(default=0)),
                ('parer_fleches', fiches.functions.IntegerRangeField(default=0)),
                ('athle', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
                ('resistant', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
                ('cc', fiches.functions.IntegerRangeField(default=0)),
                ('prot', fiches.functions.IntegerRangeField(default=0)),
                ('epeiste', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
                ('crane_dur', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
                ('equitation', fiches.functions.IntegerRangeField(default=0)),
                ('maitr_glaive', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
                ('maitr_arm_lourde', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
                ('feroce', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
                ('implacable', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fiche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('autres_prenoms', models.CharField(default=b'Aucun', max_length=200)),
                ('titre', models.CharField(default=b'Aucun', max_length=75)),
                ('autres_titres', models.CharField(default=b'Aucun', max_length=500)),
                ('sexe', models.CharField(choices=[(b'h', b'Homme'), (b'f', b'Femme')], default=b'Homme', max_length=1)),
                ('race', models.CharField(default=b'Humaine', max_length=40)),
                ('taille', models.FloatField(default=b'1.70')),
                ('poids', models.FloatField(default=b'70')),
                ('profession', models.CharField(default=b'Prostipute', max_length=75)),
                ('medailles', models.CharField(default=b'Non applicable/Aucune', max_length=3000)),
                ('etat', models.CharField(choices=[(b'VI', b'Vivant'), (b'MO', b'Mort'), (b'DI', b'Disparu')], default=b'VI', max_length=2)),
                ('pj', models.CharField(choices=[(b'p', b'Personnage jou\xc3\xa9'), (b'a', b'Personnage jouable'), (b'n', b'Personnage non jou\xc3\xa9')], default=b'Personnage jou\xc3\xa9', max_length=1)),
                ('jour_de_naissance', fiches.functions.IntegerRangeField(default=b'1')),
                ('mois_de_naissance', fiches.functions.IntegerRangeField(default=b'1')),
                ('annee_de_naissance', fiches.functions.IntegerRangeField(default=b'0')),
                ('zone_de_naissance', models.SmallIntegerField(choices=[(b"Royaumes de l'est", [(0, b'Bois de la P\xc3\xa9nombre'), (1, b'Bois des Chants \xc3\xa9ternels'), (2, b'Cap Strangleronce'), (3, b'Clairi\xc3\xa8res de Tirisfal'), (4, b'Contreforts de Hautebrande'), (5, b'Dun Morogh'), (6, b'D\xc3\xa9fil\xc3\xa9 de Deuillevent'), (7, b"For\xc3\xaat d'Elwynn"), (8, b'For\xc3\xaat des Pins-Argent\xc3\xa9s'), (9, b'Giln\xc3\xa9as'), (10, b'Gorge des Vents br\xc3\xbblants'), (11, b'Hautes-terres Arathies'), (12, b'Hautes-terres du Cr\xc3\xa9puscule'), (13, b"Kul'Tiras"), (14, b'Les Carmines'), (15, b'Les Hinterlands'), (16, b'Les Paluns'), (17, b'Les terres Fant\xc3\xb4mes'), (18, b'Loch Modan'), (19, b"Maleterres de l'Est"), (20, b"Maleterres de l'Ouest"), (21, b'Marais des Chagrins'), (22, b"Marche de l'Ouest"), (23, b'Noirebois'), (24, b'Steppes Ardentes'), (25, b'Strangleronce septentrionale'), (26, b'Terres Foudroy\xc3\xa9es'), (27, b'Terres Ingrates'), (28, b"\xc3\x8ele de Quel'Danas")]), (b'Kalimdor', [(100, b'Azshara'), (101, b"Berceau-de-l'Hiver"), (102, b"Crat\xc3\xa8re d'Un'Goro"), (103, b'Durotar'), (104, b'D\xc3\xa9solace'), (105, b'F\xc3\xa9ralas'), (106, b'Gangrebois'), (107, b'Les Serres-Rocheuses'), (108, b"Mar\xc3\xa9cage d'\xc3\x82prefange"), (109, b'Mille pointes'), (110, b'Mont Hyjal'), (111, b'Mulgore'), (112, b'Orneval'), (113, b'Reflet-de-Lune'), (114, b'Silithus'), (115, b'Sombrivage'), (116, b'Tanaris'), (117, b'Tarides du Nord'), (118, b'Tarides du Sud'), (119, b'Teldrassil'), (120, b'Uldum'), (121, b"\xc3\x8eles de l'\xc3\x89cho")]), (b'Norfendre', [(200, b'Bassin de Sholazar'), (201, b'D\xc3\xa9solation des dragons'), (202, b'Fjord Hurlant'), (203, b'For\xc3\xaat du Chant de cristal'), (204, b"Joug-d'hiver"), (205, b'La Couronne de glace'), (206, b'Les Grisonnes'), (207, b'Les pics Foudroy\xc3\xa9s'), (208, b'Toundra Bor\xc3\xa9enne'), (209, b"Zul'Drak")]), (b'Pandarie', [(300, b'D\xc3\xa9sert de Tanlong'), (301, b'Etendues sauvages de Krasarang'), (302, b'La for\xc3\xaat de Jade'), (303, b'Sommet de Kun-Lai'), (304, b"Terres de l'Angoisse"), (305, b"Val de l'Eternel Printemps"), (306, b'Vall\xc3\xa9e des Quatre vents')]), (b'Iles bris\xc3\xa9es', [(400, b'Azsuna'), (401, b'Haut-Roc'), (402, b'Suramar'), (403, b'Tornheim'), (404, b"Val'Sharah")]), (b'Kezan', [(500, b'Kezan')]), (b'Zandalar', [(600, b'Zandalar')])], default=23, null=True)),
                ('ville_de_naissance', models.CharField(default=b'Inconnue', max_length=50)),
                ('zone_de_residence', models.SmallIntegerField(choices=[(b"Royaumes de l'est", [(0, b'Bois de la P\xc3\xa9nombre'), (1, b'Bois des Chants \xc3\xa9ternels'), (2, b'Cap Strangleronce'), (3, b'Clairi\xc3\xa8res de Tirisfal'), (4, b'Contreforts de Hautebrande'), (5, b'Dun Morogh'), (6, b'D\xc3\xa9fil\xc3\xa9 de Deuillevent'), (7, b"For\xc3\xaat d'Elwynn"), (8, b'For\xc3\xaat des Pins-Argent\xc3\xa9s'), (9, b'Giln\xc3\xa9as'), (10, b'Gorge des Vents br\xc3\xbblants'), (11, b'Hautes-terres Arathies'), (12, b'Hautes-terres du Cr\xc3\xa9puscule'), (13, b"Kul'Tiras"), (14, b'Les Carmines'), (15, b'Les Hinterlands'), (16, b'Les Paluns'), (17, b'Les terres Fant\xc3\xb4mes'), (18, b'Loch Modan'), (19, b"Maleterres de l'Est"), (20, b"Maleterres de l'Ouest"), (21, b'Marais des Chagrins'), (22, b"Marche de l'Ouest"), (23, b'Noirebois'), (24, b'Steppes Ardentes'), (25, b'Strangleronce septentrionale'), (26, b'Terres Foudroy\xc3\xa9es'), (27, b'Terres Ingrates'), (28, b"\xc3\x8ele de Quel'Danas")]), (b'Kalimdor', [(100, b'Azshara'), (101, b"Berceau-de-l'Hiver"), (102, b"Crat\xc3\xa8re d'Un'Goro"), (103, b'Durotar'), (104, b'D\xc3\xa9solace'), (105, b'F\xc3\xa9ralas'), (106, b'Gangrebois'), (107, b'Les Serres-Rocheuses'), (108, b"Mar\xc3\xa9cage d'\xc3\x82prefange"), (109, b'Mille pointes'), (110, b'Mont Hyjal'), (111, b'Mulgore'), (112, b'Orneval'), (113, b'Reflet-de-Lune'), (114, b'Silithus'), (115, b'Sombrivage'), (116, b'Tanaris'), (117, b'Tarides du Nord'), (118, b'Tarides du Sud'), (119, b'Teldrassil'), (120, b'Uldum'), (121, b"\xc3\x8eles de l'\xc3\x89cho")]), (b'Norfendre', [(200, b'Bassin de Sholazar'), (201, b'D\xc3\xa9solation des dragons'), (202, b'Fjord Hurlant'), (203, b'For\xc3\xaat du Chant de cristal'), (204, b"Joug-d'hiver"), (205, b'La Couronne de glace'), (206, b'Les Grisonnes'), (207, b'Les pics Foudroy\xc3\xa9s'), (208, b'Toundra Bor\xc3\xa9enne'), (209, b"Zul'Drak")]), (b'Pandarie', [(300, b'D\xc3\xa9sert de Tanlong'), (301, b'Etendues sauvages de Krasarang'), (302, b'La for\xc3\xaat de Jade'), (303, b'Sommet de Kun-Lai'), (304, b"Terres de l'Angoisse"), (305, b"Val de l'Eternel Printemps"), (306, b'Vall\xc3\xa9e des Quatre vents')]), (b'Iles bris\xc3\xa9es', [(400, b'Azsuna'), (401, b'Haut-Roc'), (402, b'Suramar'), (403, b'Tornheim'), (404, b"Val'Sharah")]), (b'Kezan', [(500, b'Kezan')]), (b'Zandalar', [(600, b'Zandalar')])], default=23, null=True)),
                ('ville_de_residence', models.CharField(default=b'Ch\xc3\xa2tellerie', max_length=50)),
                ('description', models.CharField(default=b'A venir', max_length=6000)),
                ('historique', models.CharField(default=b'A venir', max_length=6000)),
                ('inventaire', models.CharField(blank=True, default=b'A venir', max_length=6000, null=True)),
                ('relations', models.CharField(default=b'Aucune', max_length=6000)),
                ('image', models.ImageField(default=b'images/site/no-image.png', upload_to=b'images/persos')),
                ('pseudo_du_personnage', models.CharField(default=b'?', max_length=30)),
                ('main_dir', models.CharField(choices=[(b'g', b'Gauche'), (b'd', b'Droite')], default=b'Droite', max_length=1)),
                ('afficher_createur', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=True)),
                ('afficher_inventaire', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=True)),
                ('afficher_pseudo', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=True)),
                ('creation', models.DateField(default=django.utils.timezone.now)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to=settings.AUTH_USER_MODEL)),
                ('equipement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proprietaire', to='fiches.Equipement')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
                'verbose_name_plural': 'fiches',
                'default_related_name': 'fiches',
                'verbose_name': 'fiche',
                'permissions': (('plus_de_15_fiches', 'Peut faire plus de quinze fiches'),),
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=b'Inventaire', max_length=50)),
                ('cases', models.ManyToManyField(related_name='inventaire', to='fiches.Case')),
            ],
            options={
                'permissions': (('inventaire_ok', 'Peut faire des inventaires'),),
                'verbose_name': 'inventaire',
                'verbose_name_plural': 'inventaires',
                'default_related_name': 'inventaire',
            },
        ),
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=75)),
                ('qualite', models.CharField(choices=[(b'm', b'M\xc3\xa9diocre'), (b'c', b'Commun'), (b'i', b'Inhabituel'), (b'r', b'Rare'), (b'e', b'Epique'), (b'l', b'L\xc3\xa9gendaire'), (b'u', b'Unique')], default=b'Commun', max_length=1)),
                ('description', models.CharField(default=b'Aucune', max_length=500)),
                ('prix', models.IntegerField(default=0)),
                ('poids', models.IntegerField(default=0)),
                ('image', models.ImageField(default=b'images/site/WoWUnknownItem01.PNG', upload_to=b'images/users')),
            ],
            options={
                'ordering': ['nom'],
                'verbose_name_plural': 'objets',
                'default_related_name': 'objet',
                'verbose_name': 'objet',
                'permissions': (('objet_ok', 'Peut faire des objets'),),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=b'images/site/no-image.png', upload_to=b'images/users')),
                ('naissance', models.DateField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fiche',
            name='inventaire_fdg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proprietaire', to='fiches.Inventaire'),
        ),
        migrations.AddField(
            model_name='case',
            name='objet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='fiches.Objet'),
        ),
        migrations.AddField(
            model_name='armure',
            name='objet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armure', to='fiches.Objet'),
        ),
    ]
