# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avant_garde',
            name='classe',
            field=models.SmallIntegerField(choices=[(1, b'Fantassin'), (2, b'Arbal\xc3\xa9trier'), (3, b'Eclaireur'), (4, b'Apothicaire de combat'), (5, b'Apprenti sorcier')], default=1),
        ),
    ]
