# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0003_auto_20170628_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='avant_garde',
            name='etat',
            field=models.CharField(choices=[(b'v', b'Vivant'), (b'm', b'Mort'), (b'd', b'Disparu')], default=b'Vivant', max_length=1),
        ),
        migrations.AddField(
            model_name='avant_garde',
            name='pj',
            field=models.CharField(choices=[(b'p', b'Personnage jou\xc3\xa9'), (b'n', b'Personnage non jou\xc3\xa9')], default=b'Personnage jou\xc3\xa9', max_length=1),
        ),
    ]
