# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0005_auto_20170629_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='c_cheveux',
            field=models.CharField(default=b'Bruns', max_length=30),
        ),
        migrations.AddField(
            model_name='fiche',
            name='c_yeux',
            field=models.CharField(default=b'Marrons', max_length=30),
        ),
    ]
