# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0006_auto_20170630_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='signes_dis',
            field=models.CharField(default=b'Aucun', max_length=200),
        ),
    ]
