# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0006_auto_20170720_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='zone_de_naissance',
            field=models.SmallIntegerField(choices=[("Royaumes de l'est", ((600, 'Bois de la Pénombre'), (601, 'Bois des Chants éternels'), (602, 'Cap Strangleronce'), (603, 'Clairières de Tirisfal'), (604, 'Contreforts de Hautebrande'), (605, 'Dun Morogh'), (606, 'Défilé de Deuillevent'), (607, "Forêt d'Elwynn"), (608, 'Forêt des Pins-Argentés'), (609, 'Gilnéas'), (610, 'Gorge des Vents brûlants'), (611, 'Hautes-terres Arathies'), (612, 'Hautes-terres du Crépuscule'), (613, "Kul'Tiras"), (614, 'Les Carmines'), (615, 'Les Hinterlands'), (616, 'Les Paluns'), (617, 'Les terres Fantômes'), (618, 'Loch Modan'), (619, "Maleterres de l'Est"), (620, "Maleterres de l'Ouest"), (621, 'Marais des Chagrins'), (622, "Marche de l'Ouest"), (623, 'Noirebois'), (624, 'Steppes Ardentes'), (625, 'Strangleronce septentrionale'), (626, 'Terres Foudroyées'), (627, 'Terres Ingrates'), (628, "Île de Quel'Danas"))), ('Kalimdor', ((600, 'Azshara'), (601, "Berceau-de-l'Hiver"), (602, "Cratère d'Un'Goro"), (603, 'Durotar'), (604, 'Désolace'), (605, 'Féralas'), (606, 'Gangrebois'), (607, 'Les Serres-Rocheuses'), (608, "Marécage d'Âprefange"), (609, 'Mille pointes'), (610, 'Mont Hyjal'), (611, 'Mulgore'), (612, 'Orneval'), (613, 'Reflet-de-Lune'), (614, 'Silithus'), (615, 'Sombrivage'), (616, 'Tanaris'), (617, 'Tarides du Nord'), (618, 'Tarides du Sud'), (619, 'Teldrassil'), (620, 'Uldum'), (621, "Îles de l'Écho"))), ('Norfendre', ((600, 'Bassin de Sholazar'), (601, 'Désolation des dragons'), (602, 'Fjord Hurlant'), (603, 'Forêt du Chant de cristal'), (604, "Joug-d'hiver"), (605, 'La Couronne de glace'), (606, 'Les Grisonnes'), (607, 'Les pics Foudroyés'), (608, 'Toundra Boréenne'), (609, "Zul'Drak"))), ('Pandarie', ((600, 'Désert de Tanlong'), (601, 'Etendues sauvages de Krasarang'), (602, 'La forêt de Jade'), (603, 'Sommet de Kun-Lai'), (604, "Terres de l'Angoisse"), (605, "Val de l'Eternel Printemps"), (606, 'Vallée des Quatre vents'))), ('Iles brisées', ((600, 'Azsuna'), (601, 'Haut-Roc'), (602, 'Suramar'), (603, 'Tornheim'), (604, "Val'Sharah"))), ('Kezan', ((600, 'Kezan'),)), ('Zandalar', ((600, 'Zandalar'),))], default=23, null=True),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='zone_de_residence',
            field=models.SmallIntegerField(choices=[("Royaumes de l'est", ()), ('Kalimdor', ()), ('Norfendre', ()), ('Pandarie', ()), ('Iles brisées', ()), ('Kezan', ()), ('Zandalar', ())], default=23, null=True),
        ),
        migrations.AlterField(
            model_name='quete',
            name='zone',
            field=models.SmallIntegerField(choices=[("Royaumes de l'est", ()), ('Kalimdor', ()), ('Norfendre', ()), ('Pandarie', ()), ('Iles brisées', ()), ('Kezan', ()), ('Zandalar', ())], default=23, null=True),
        ),
    ]
