# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0007_fiche_signes_dis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='c_cheveux',
            field=models.CharField(default=b'Brun', max_length=30),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='c_yeux',
            field=models.CharField(default=b'Marron', max_length=30),
        ),
    ]
