# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0008_auto_20170630_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avant_garde',
            options={'ordering': ['nom', 'prenom'], 'permissions': (('avant_garde', "A acc\xe8s \xe0 l'avant-garde"),)},
        ),
    ]
