# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fiches', '0009_auto_20170630_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='avant_garde',
            name='createur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avant_garde', to=settings.AUTH_USER_MODEL),
        ),
    ]
