# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0010_avant_garde_createur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avantages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=b'Aucun', max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('points', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
