# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0010_auto_20141228_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='medaille',
            field=models.CharField(default=b'Non applicable/Aucune', max_length=3000),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='pj',
            field=models.CharField(choices=[(b'p', b'Personnage jou\xc3\xa9'), (b'a', b'Personnage jouable'), (b'n', b'Personnage non jou\xc3\xa9')], default=b'Personnage jou\xc3\xa9', max_length=1),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='race',
            field=models.CharField(default=b'Humaine', max_length=40),
        ),
    ]
