# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0011_auto_20170430_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='image',
            field=models.ImageField(default=b'pics/no-image.png', upload_to=b'pics/'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='sexe',
            field=models.CharField(choices=[(b'h', b'Masculin'), (b'f', b'F\xc3\xa9minin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='titre',
            field=models.CharField(default=b'Aucun', max_length=75),
        ),
    ]
