# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0012_auto_20170502_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='image',
            field=models.ImageField(default=b'static/pics/no-image.png', upload_to=b'static/pics/'),
        ),
    ]
