# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0013_auto_20170705_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avant_garde',
            name='avants',
            field=models.ManyToManyField(to='fiches.Avantages'),
        ),
        migrations.AlterField(
            model_name='avant_garde',
            name='desavants',
            field=models.ManyToManyField(to='fiches.Desavantages'),
        ),
    ]
