# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0013_auto_20170502_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiche',
            name='prenom2',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='prenom3',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='prenom4',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='prenom5',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='prenom6',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='prenom7',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='prenom8',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='titre2',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='titre3',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='titre4',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='titre5',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='titre6',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='titre7',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='titre8',
        ),
        migrations.AddField(
            model_name='fiche',
            name='autresprenoms',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='fiche',
            name='autrestitres',
            field=models.CharField(default=b'', max_length=500),
        ),
    ]
