# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0014_auto_20170503_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='image',
            field=models.ImageField(default=b'images/no-image.png', upload_to=b'images/'),
        ),
    ]
