# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0014_auto_20170705_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avantages',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='desavantages',
            options={'ordering': ['nom']},
        ),
    ]
