# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0015_auto_20170706_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='avant_garde',
            name='dependances',
            field=models.CharField(blank=True, default=b'Sans', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='avant_garde',
            name='peur',
            field=models.CharField(blank=True, default=b'Sans', max_length=80, null=True),
        ),
    ]
