# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0015_auto_20170503_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='image',
            field=models.ImageField(default=b'/static/fiches/images/no-image.png', upload_to=b'images/'),
        ),
    ]
