# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0018_auto_20170709_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armure',
            name='membre',
            field=models.SmallIntegerField(choices=[(1, b'Main principale'), (2, b'Autre main'), (3, b'T\xc3\xaate'), (4, b'Epaules'), (5, b'Torse'), (6, b'Mains'), (7, b'Taille'), (8, b'Jambes'), (9, b'Pieds'), (10, b'Dos'), (11, b'Cou'), (12, b'Doigt'), (13, b'Poignets'), (14, b'Divers'), (15, b'Arme de secours')], default=5),
        ),
    ]
