# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0019_auto_20170710_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='nom',
            field=models.CharField(default=b'Equipement ', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='nom',
            field=models.CharField(default=b'Inventaire ', max_length=50),
        ),
    ]
