# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0020_auto_20170710_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apothicaire',
            name='enfumeur',
        ),
        migrations.RemoveField(
            model_name='apothicaire',
            name='lancer_fioles',
        ),
        migrations.RemoveField(
            model_name='apothicaire',
            name='maitr_guerisseur',
        ),
        migrations.RemoveField(
            model_name='apothicaire',
            name='maitr_scalpel',
        ),
        migrations.RemoveField(
            model_name='eclaireur',
            name='art_silenc',
        ),
        migrations.RemoveField(
            model_name='eclaireur',
            name='oeil_aigle',
        ),
        migrations.RemoveField(
            model_name='eclaireur',
            name='rodeur',
        ),
        migrations.RemoveField(
            model_name='eclaireur',
            name='rx_eclairs',
        ),
        migrations.RemoveField(
            model_name='eclaireur',
            name='vif',
        ),
        migrations.RemoveField(
            model_name='eclaireur',
            name='vigilant',
        ),
        migrations.RemoveField(
            model_name='fantassin',
            name='athle',
        ),
        migrations.RemoveField(
            model_name='fantassin',
            name='crane_dur',
        ),
        migrations.RemoveField(
            model_name='fantassin',
            name='epeiste',
        ),
        migrations.RemoveField(
            model_name='fantassin',
            name='feroce',
        ),
        migrations.RemoveField(
            model_name='fantassin',
            name='implacable',
        ),
        migrations.RemoveField(
            model_name='fantassin',
            name='maitr_arm_lourde',
        ),
        migrations.RemoveField(
            model_name='fantassin',
            name='maitr_glaive',
        ),
        migrations.RemoveField(
            model_name='fantassin',
            name='resistant',
        ),
        migrations.AddField(
            model_name='apothicaire',
            name='guerisseur_enfum',
            field=models.SmallIntegerField(choices=[(1, b'Niveau inf\xc3\xa9rieur'), (2, b'Ma\xc3\xaetre gu\xc3\xa9risseur'), (3, b'Enfumeur')], default=1),
        ),
        migrations.AddField(
            model_name='apothicaire',
            name='scalpel_fioles',
            field=models.SmallIntegerField(choices=[(1, b'Niveau inf\xc3\xa9rieur'), (2, b'Ma\xc3\xaetrise du scalpel'), (3, b'Art du lancer de fioles')], default=1),
        ),
        migrations.AddField(
            model_name='eclaireur',
            name='aigle_vif',
            field=models.SmallIntegerField(choices=[(1, b'Niveau inf\xc3\xa9rieur'), (2, b"\xc5\x92il d'aigle"), (3, b'Vif')], default=1),
        ),
        migrations.AddField(
            model_name='eclaireur',
            name='silen_rodeur',
            field=models.SmallIntegerField(choices=[(1, b'Niveau inf\xc3\xa9rieur'), (2, b'Art de la mort silencieuse'), (3, b'R\xc3\xb4deur')], default=1),
        ),
        migrations.AddField(
            model_name='eclaireur',
            name='vigilant_rx',
            field=models.SmallIntegerField(choices=[(1, b'Niveau inf\xc3\xa9rieur'), (2, b'Vigilant'), (3, b'R\xc3\xa9flexes \xc3\xa9claireurs')], default=1),
        ),
        migrations.AddField(
            model_name='fantassin',
            name='athle_resi',
            field=models.SmallIntegerField(choices=[(1, b'Niveau inf\xc3\xa9rieur'), (2, b'Athl\xc3\xa9tisme'), (3, b'R\xc3\xa9sistant')], default=1),
        ),
        migrations.AddField(
            model_name='fantassin',
            name='epe_craned',
            field=models.SmallIntegerField(choices=[(1, b'Niveau inf\xc3\xa9rieur'), (2, b'Ep\xc3\xa9iste'), (3, b'Cr\xc3\xa2ne d\xc3\xbbr')], default=1),
        ),
        migrations.AddField(
            model_name='fantassin',
            name='feroce_impla',
            field=models.SmallIntegerField(choices=[(1, b'Niveau inf\xc3\xa9rieur'), (2, b'F\xc3\xa9roce'), (3, b'Implacable')], default=1),
        ),
        migrations.AddField(
            model_name='fantassin',
            name='glaive_lourde',
            field=models.SmallIntegerField(choices=[(1, b'Niveau inf\xc3\xa9rieur'), (2, b'Ma\xc3\xaetriste du glaive'), (3, b"Ma\xc3\xaetrise de l'armure lourde")], default=1),
        ),
    ]
