# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import fiches.functions


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0021_auto_20170712_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('mois_debut', fiches.functions.IntegerRangeField(default=b'1')),
                ('mois_fin', fiches.functions.IntegerRangeField(default=b'1')),
                ('annee_debut', fiches.functions.IntegerRangeField(default=b'37')),
                ('annee_fin', fiches.functions.IntegerRangeField(default=b'37')),
                ('objectif', models.CharField(max_length=100)),
                ('image', models.ImageField(default=b'images/site/avant-garde.jpg', upload_to=b'images/rpg/campagne')),
            ],
        ),
        migrations.AddField(
            model_name='avant_garde',
            name='campagne',
            field=models.ManyToManyField(to='fiches.Campagne'),
        ),
    ]
