# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0021_auto_20170511_1553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
