# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0022_auto_20170712_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='fini',
            field=models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False),
        ),
    ]
