# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 18:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fiches', '0022_auto_20170513_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='aff_utilisateur',
            field=models.CharField(choices=[(b'o', b'Oui'), (b'n', b'Non')], default=b'Oui', max_length=1),
        ),
        migrations.AddField(
            model_name='fiche',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
