# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0023_auto_20170514_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiche',
            old_name='utilisateur',
            new_name='createur',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='aff_utilisateur',
        ),
        migrations.AddField(
            model_name='fiche',
            name='aff_createur',
            field=models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=True),
        ),
    ]
