# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0023_campagne_fini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='objectif',
            field=models.CharField(default=b'Tuer.', max_length=100),
        ),
    ]
