# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0024_auto_20170514_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiche',
            old_name='annee_naissance',
            new_name='annee_de_naissance',
        ),
        migrations.RenameField(
            model_name='fiche',
            old_name='autresprenoms',
            new_name='autres_prenoms',
        ),
        migrations.RenameField(
            model_name='fiche',
            old_name='autrestitres',
            new_name='autres_titres',
        ),
        migrations.RenameField(
            model_name='fiche',
            old_name='jour_naissance',
            new_name='jour_de_naissance',
        ),
        migrations.RenameField(
            model_name='fiche',
            old_name='mois_naissance',
            new_name='mois_de_naissance',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='zone_naissance',
        ),
        migrations.AddField(
            model_name='fiche',
            name='inventaire',
            field=models.CharField(default=b'A venir', max_length=6000),
        ),
        migrations.AddField(
            model_name='fiche',
            name='relations',
            field=models.CharField(default=b'A venir', max_length=6000),
        ),
        migrations.AddField(
            model_name='fiche',
            name='ville_de_naissance',
            field=models.CharField(default=b'Inconnu', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='ville_de_residence',
            field=models.CharField(default=b'Noirebois', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='zone_de_naissance',
            field=models.SmallIntegerField(choices=[(b"Royaumes de l'est", [(0, b'Bois de la P\xc3\xa9nombre'), (1, b'Bois des Chants \xc3\xa9ternels'), (2, b'Cap Strangleronce'), (3, b'Clairi\xc3\xa8res de Tirisfal'), (4, b'Contreforts de Hautebrande'), (5, b'Dun Morogh'), (6, b'D\xc3\xa9fil\xc3\xa9 de Deuillevent'), (7, b"For\xc3\xaat d'Elwynn"), (8, b'For\xc3\xaat des Pins-Argent\xc3\xa9s'), (9, b'Giln\xc3\xa9as'), (10, b'Gorge des Vents br\xc3\xbblants'), (11, b'Hautes-terres Arathies'), (12, b'Hautes-terres du Cr\xc3\xa9puscule'), (13, b"Kul'Tiras"), (14, b'Les Carmines'), (15, b'Les Hinterlands'), (16, b'Les Paluns'), (17, b'Les terres Fant\xc3\xb4mes'), (18, b'Loch Modan'), (19, b"Maleterres de l'Est"), (20, b"Maleterres de l'Ouest"), (21, b'Marais des Chagrins'), (22, b"Marche de l'Ouest"), (23, b'Noirebois'), (24, b'Steppes Ardentes'), (25, b'Strangleronce septentrionale'), (26, b'Terres Foudroy\xc3\xa9es'), (27, b'Terres Ingrates'), (28, b"\xc3\x8ele de Quel'Danas")]), (b'Kalimdor', [(100, b'Azshara'), (101, b"Berceau-de-l'Hiver"), (102, b"Crat\xc3\xa8re d'Un'Goro"), (103, b'Durotar'), (104, b'D\xc3\xa9solace'), (105, b'F\xc3\xa9ralas'), (106, b'Gangrebois'), (107, b'Les Serres-Rocheuses'), (108, b"Mar\xc3\xa9cage d'\xc3\x82prefange"), (109, b'Mille pointes'), (110, b'Mont Hyjal'), (111, b'Mulgore'), (112, b'Orneval'), (113, b'Reflet-de-Lune'), (114, b'Silithus'), (115, b'Sombrivage'), (116, b'Tanaris'), (117, b'Tarides du Nord'), (118, b'Tarides du Sud'), (119, b'Teldrassil'), (120, b'Uldum'), (121, b"\xc3\x8eles de l'\xc3\x89cho")]), (b'Norfendre', [(200, b'Bassin de Sholazar'), (201, b'D\xc3\xa9solation des dragons'), (202, b'Fjord Hurlant'), (203, b'For\xc3\xaat du Chant de cristal'), (204, b"Joug-d'hiver"), (205, b'La Couronne de glace'), (206, b'Les Grisonnes'), (207, b'Les pics Foudroy\xc3\xa9s'), (208, b'Toundra Bor\xc3\xa9enne'), (209, b"Zul'Drak")]), (b'Pandarie', [(300, b'D\xc3\xa9sert de Tanlong'), (301, b'Etendues sauvages de Krasarang'), (302, b'La for\xc3\xaat de Jade'), (303, b'Sommet de Kun-Lai'), (304, b"Terres de l'Angoisse"), (305, b"Val de l'Eternel Printemps"), (306, b'Vall\xc3\xa9e des Quatre vents')]), (b'Iles bris\xc3\xa9es', [(400, b'Azsuna'), (401, b'Haut-Roc'), (402, b'Suramar'), (403, b'Tornheim'), (404, b"Val'Sharah")]), (b'Kezan', [(500, b'K'), (501, b'e'), (502, b'z'), (503, b'a'), (504, b'n')]), (b'Zandalar', [(600, b'Z'), (601, b'a'), (602, b'n'), (603, b'd'), (604, b'a'), (605, b'l'), (606, b'a'), (607, b'r')])], null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='zone_de_residence',
            field=models.SmallIntegerField(choices=[(b"Royaumes de l'est", [(0, b'Bois de la P\xc3\xa9nombre'), (1, b'Bois des Chants \xc3\xa9ternels'), (2, b'Cap Strangleronce'), (3, b'Clairi\xc3\xa8res de Tirisfal'), (4, b'Contreforts de Hautebrande'), (5, b'Dun Morogh'), (6, b'D\xc3\xa9fil\xc3\xa9 de Deuillevent'), (7, b"For\xc3\xaat d'Elwynn"), (8, b'For\xc3\xaat des Pins-Argent\xc3\xa9s'), (9, b'Giln\xc3\xa9as'), (10, b'Gorge des Vents br\xc3\xbblants'), (11, b'Hautes-terres Arathies'), (12, b'Hautes-terres du Cr\xc3\xa9puscule'), (13, b"Kul'Tiras"), (14, b'Les Carmines'), (15, b'Les Hinterlands'), (16, b'Les Paluns'), (17, b'Les terres Fant\xc3\xb4mes'), (18, b'Loch Modan'), (19, b"Maleterres de l'Est"), (20, b"Maleterres de l'Ouest"), (21, b'Marais des Chagrins'), (22, b"Marche de l'Ouest"), (23, b'Noirebois'), (24, b'Steppes Ardentes'), (25, b'Strangleronce septentrionale'), (26, b'Terres Foudroy\xc3\xa9es'), (27, b'Terres Ingrates'), (28, b"\xc3\x8ele de Quel'Danas")]), (b'Kalimdor', [(100, b'Azshara'), (101, b"Berceau-de-l'Hiver"), (102, b"Crat\xc3\xa8re d'Un'Goro"), (103, b'Durotar'), (104, b'D\xc3\xa9solace'), (105, b'F\xc3\xa9ralas'), (106, b'Gangrebois'), (107, b'Les Serres-Rocheuses'), (108, b"Mar\xc3\xa9cage d'\xc3\x82prefange"), (109, b'Mille pointes'), (110, b'Mont Hyjal'), (111, b'Mulgore'), (112, b'Orneval'), (113, b'Reflet-de-Lune'), (114, b'Silithus'), (115, b'Sombrivage'), (116, b'Tanaris'), (117, b'Tarides du Nord'), (118, b'Tarides du Sud'), (119, b'Teldrassil'), (120, b'Uldum'), (121, b"\xc3\x8eles de l'\xc3\x89cho")]), (b'Norfendre', [(200, b'Bassin de Sholazar'), (201, b'D\xc3\xa9solation des dragons'), (202, b'Fjord Hurlant'), (203, b'For\xc3\xaat du Chant de cristal'), (204, b"Joug-d'hiver"), (205, b'La Couronne de glace'), (206, b'Les Grisonnes'), (207, b'Les pics Foudroy\xc3\xa9s'), (208, b'Toundra Bor\xc3\xa9enne'), (209, b"Zul'Drak")]), (b'Pandarie', [(300, b'D\xc3\xa9sert de Tanlong'), (301, b'Etendues sauvages de Krasarang'), (302, b'La for\xc3\xaat de Jade'), (303, b'Sommet de Kun-Lai'), (304, b"Terres de l'Angoisse"), (305, b"Val de l'Eternel Printemps"), (306, b'Vall\xc3\xa9e des Quatre vents')]), (b'Iles bris\xc3\xa9es', [(400, b'Azsuna'), (401, b'Haut-Roc'), (402, b'Suramar'), (403, b'Tornheim'), (404, b"Val'Sharah")]), (b'Kezan', [(500, b'K'), (501, b'e'), (502, b'z'), (503, b'a'), (504, b'n')]), (b'Zandalar', [(600, b'Z'), (601, b'a'), (602, b'n'), (603, b'd'), (604, b'a'), (605, b'l'), (606, b'a'), (607, b'r')])], null=True),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='createur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='description',
            field=models.CharField(default=b'A venir', max_length=6000),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='historique',
            field=models.CharField(default=b'A venir', max_length=6000),
        ),
    ]
