# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0026_auto_20170515_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='aff_inventaire',
            field=models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=True),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='relations',
            field=models.CharField(default=b'Aucune', max_length=6000),
        ),
    ]
