# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0027_auto_20170515_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='pseudo',
            field=models.CharField(default=b'?', max_length=30),
        ),
    ]
