# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0027_quete_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quete',
            name='accomplie',
        ),
        migrations.AddField(
            model_name='quete',
            name='etat',
            field=models.SmallIntegerField(choices=[(1, b'En attente'), (2, b'R\xc3\xa9serv\xc3\xa9e'), (3, b'Accomplie')], default=1),
        ),
        migrations.AlterField(
            model_name='quete',
            name='objectif',
            field=models.CharField(max_length=600),
        ),
    ]
