# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0029_auto_20170714_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quete',
            name='ennemi',
            field=models.ImageField(default=b'images/site/quest/Portraits/FollowerPortrait_NoPortrait.png', upload_to=b'images/site/quest/ennemis'),
        ),
    ]
