# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0031_auto_20170721_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apothicaire',
            name='guerisseur_enfum',
            field=models.SmallIntegerField(choices=[(1, b'Niveau inf\xc3\xa9rieur'), (2, b'Ma\xc3\xaetre gu\xc3\xa9risseur'), (3, b'Enfumeur')], default=1),
        ),
        migrations.AlterField(
            model_name='apothicaire',
            name='scalpel_fioles',
            field=models.SmallIntegerField(choices=[(1, b'Niveau inf\xc3\xa9rieur'), (2, b'Ma\xc3\xaetrise du scalpel'), (3, b'Art du lancer de fioles')], default=1),
        ),
        migrations.AlterField(
            model_name='armure',
            name='membre',
            field=models.SmallIntegerField(choices=[(1, b'Main principale'), (2, b'Autre main'), (3, b'T\xc3\xaate'), (4, b'Epaules'), (5, b'Torse'), (6, b'Mains'), (7, b'Taille'), (8, b'Jambes'), (9, b'Pieds'), (10, b'Dos'), (11, b'Cou'), (12, b'Doigt'), (13, b'Poignets'), (14, b'Divers'), (15, b'Arme de secours')], default=5),
        ),
        migrations.AlterField(
            model_name='avant_garde',
            name='classe',
            field=models.SmallIntegerField(choices=[(1, b'Fantassin'), (2, b'Arbal\xc3\xa9trier'), (3, b'Eclaireur'), (4, b'Apothicaire de combat'), (5, b'Apprenti sorcier')], default=1),
        ),
        migrations.AlterField(
            model_name='avant_garde',
            name='ex_prof',
            field=models.SmallIntegerField(choices=[(1, b'Forgeron'), (2, b'Chasseur'), (3, b'Cuisinier'), (4, b'Tavernier'), (5, b"Facteur d'arc"), (6, b'Tanneur'), (7, b'Architecte'), (8, b'Eb\xc3\xa9niste'), (9, b'Autre m\xc3\xa9tier')], default=9),
        ),
        migrations.AlterField(
            model_name='avant_garde',
            name='pj',
            field=models.CharField(choices=[(b'p', b'Personnage jou\xc3\xa9'), (b'n', b'Personnage non jou\xc3\xa9')], default=b'Personnage jou\xc3\xa9', max_length=1),
        ),
        migrations.AlterField(
            model_name='eclaireur',
            name='aigle_vif',
            field=models.SmallIntegerField(choices=[(1, b'Niveau inf\xc3\xa9rieur'), (2, b"\xc5\x92il d'aigle"), (3, b'Vif')], default=1),
        ),
        migrations.AlterField(
            model_name='eclaireur',
            name='silen_rodeur',
            field=models.SmallIntegerField(choices=[(1, b'Niveau inf\xc3\xa9rieur'), (2, b'Art de la mort silencieuse'), (3, b'R\xc3\xb4deur')], default=1),
        ),
        migrations.AlterField(
            model_name='eclaireur',
            name='vigilant_rx',
            field=models.SmallIntegerField(choices=[(1, b'Niveau inf\xc3\xa9rieur'), (2, b'Vigilant'), (3, b'R\xc3\xa9flexes \xc3\xa9claireurs')], default=1),
        ),
        migrations.AlterField(
            model_name='fantassin',
            name='athle_resi',
            field=models.SmallIntegerField(choices=[(1, b'Niveau inf\xc3\xa9rieur'), (2, b'Athl\xc3\xa9tisme'), (3, b'R\xc3\xa9sistant')], default=1),
        ),
        migrations.AlterField(
            model_name='fantassin',
            name='epe_craned',
            field=models.SmallIntegerField(choices=[(1, b'Niveau inf\xc3\xa9rieur'), (2, b'Ep\xc3\xa9iste'), (3, b'Cr\xc3\xa2ne d\xc3\xbbr')], default=1),
        ),
        migrations.AlterField(
            model_name='fantassin',
            name='feroce_impla',
            field=models.SmallIntegerField(choices=[(1, b'Niveau inf\xc3\xa9rieur'), (2, b'F\xc3\xa9roce'), (3, b'Implacable')], default=1),
        ),
        migrations.AlterField(
            model_name='fantassin',
            name='glaive_lourde',
            field=models.SmallIntegerField(choices=[(1, b'Niveau inf\xc3\xa9rieur'), (2, b'Ma\xc3\xaetriste du glaive'), (3, b"Ma\xc3\xaetrise de l'armure lourde")], default=1),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='pj',
            field=models.CharField(choices=[(b'p', b'Personnage jou\xc3\xa9'), (b'a', b'Personnage jouable'), (b'n', b'Personnage non jou\xc3\xa9')], default=b'Personnage jou\xc3\xa9', max_length=1),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='ville_de_residence',
            field=models.CharField(default=b'Ch\xc3\xa2tellerie', max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='zone_de_naissance',
            field=models.SmallIntegerField(choices=[(b"Royaumes de l'est", [(0, b'Bois de la P\xc3\xa9nombre'), (1, b'Bois des Chants \xc3\xa9ternels'), (2, b'Cap Strangleronce'), (3, b'Clairi\xc3\xa8res de Tirisfal'), (4, b'Contreforts de Hautebrande'), (5, b'Dun Morogh'), (6, b'D\xc3\xa9fil\xc3\xa9 de Deuillevent'), (7, b"For\xc3\xaat d'Elwynn"), (8, b'For\xc3\xaat des Pins-Argent\xc3\xa9s'), (9, b'Giln\xc3\xa9as'), (10, b'Gorge des Vents br\xc3\xbblants'), (11, b'Hautes-terres Arathies'), (12, b'Hautes-terres du Cr\xc3\xa9puscule'), (13, b"Kul'Tiras"), (14, b'Les Carmines'), (15, b'Les Hinterlands'), (16, b'Les Paluns'), (17, b'Les terres Fant\xc3\xb4mes'), (18, b'Loch Modan'), (19, b"Maleterres de l'Est"), (20, b"Maleterres de l'Ouest"), (21, b'Marais des Chagrins'), (22, b"Marche de l'Ouest"), (23, b'Noirebois'), (24, b'Steppes Ardentes'), (25, b'Strangleronce septentrionale'), (26, b'Terres Foudroy\xc3\xa9es'), (27, b'Terres Ingrates'), (28, b"\xc3\x8ele de Quel'Danas")]), (b'Kalimdor', [(100, b'Azshara'), (101, b"Berceau-de-l'Hiver"), (102, b"Crat\xc3\xa8re d'Un'Goro"), (103, b'Durotar'), (104, b'D\xc3\xa9solace'), (105, b'F\xc3\xa9ralas'), (106, b'Gangrebois'), (107, b'Les Serres-Rocheuses'), (108, b"Mar\xc3\xa9cage d'\xc3\x82prefange"), (109, b'Mille pointes'), (110, b'Mont Hyjal'), (111, b'Mulgore'), (112, b'Orneval'), (113, b'Reflet-de-Lune'), (114, b'Silithus'), (115, b'Sombrivage'), (116, b'Tanaris'), (117, b'Tarides du Nord'), (118, b'Tarides du Sud'), (119, b'Teldrassil'), (120, b'Uldum'), (121, b"\xc3\x8eles de l'\xc3\x89cho")]), (b'Norfendre', [(200, b'Bassin de Sholazar'), (201, b'D\xc3\xa9solation des dragons'), (202, b'Fjord Hurlant'), (203, b'For\xc3\xaat du Chant de cristal'), (204, b"Joug-d'hiver"), (205, b'La Couronne de glace'), (206, b'Les Grisonnes'), (207, b'Les pics Foudroy\xc3\xa9s'), (208, b'Toundra Bor\xc3\xa9enne'), (209, b"Zul'Drak")]), (b'Pandarie', [(300, b'D\xc3\xa9sert de Tanlong'), (301, b'Etendues sauvages de Krasarang'), (302, b'La for\xc3\xaat de Jade'), (303, b'Sommet de Kun-Lai'), (304, b"Terres de l'Angoisse"), (305, b"Val de l'Eternel Printemps"), (306, b'Vall\xc3\xa9e des Quatre vents')]), (b'Iles bris\xc3\xa9es', [(400, b'Azsuna'), (401, b'Haut-Roc'), (402, b'Suramar'), (403, b'Tornheim'), (404, b"Val'Sharah")]), (b'Kezan', [(500, b'Kezan')]), (b'Zandalar', [(600, b'Zandalar')])], default=23, null=True),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='zone_de_residence',
            field=models.SmallIntegerField(choices=[(b"Royaumes de l'est", [(0, b'Bois de la P\xc3\xa9nombre'), (1, b'Bois des Chants \xc3\xa9ternels'), (2, b'Cap Strangleronce'), (3, b'Clairi\xc3\xa8res de Tirisfal'), (4, b'Contreforts de Hautebrande'), (5, b'Dun Morogh'), (6, b'D\xc3\xa9fil\xc3\xa9 de Deuillevent'), (7, b"For\xc3\xaat d'Elwynn"), (8, b'For\xc3\xaat des Pins-Argent\xc3\xa9s'), (9, b'Giln\xc3\xa9as'), (10, b'Gorge des Vents br\xc3\xbblants'), (11, b'Hautes-terres Arathies'), (12, b'Hautes-terres du Cr\xc3\xa9puscule'), (13, b"Kul'Tiras"), (14, b'Les Carmines'), (15, b'Les Hinterlands'), (16, b'Les Paluns'), (17, b'Les terres Fant\xc3\xb4mes'), (18, b'Loch Modan'), (19, b"Maleterres de l'Est"), (20, b"Maleterres de l'Ouest"), (21, b'Marais des Chagrins'), (22, b"Marche de l'Ouest"), (23, b'Noirebois'), (24, b'Steppes Ardentes'), (25, b'Strangleronce septentrionale'), (26, b'Terres Foudroy\xc3\xa9es'), (27, b'Terres Ingrates'), (28, b"\xc3\x8ele de Quel'Danas")]), (b'Kalimdor', [(100, b'Azshara'), (101, b"Berceau-de-l'Hiver"), (102, b"Crat\xc3\xa8re d'Un'Goro"), (103, b'Durotar'), (104, b'D\xc3\xa9solace'), (105, b'F\xc3\xa9ralas'), (106, b'Gangrebois'), (107, b'Les Serres-Rocheuses'), (108, b"Mar\xc3\xa9cage d'\xc3\x82prefange"), (109, b'Mille pointes'), (110, b'Mont Hyjal'), (111, b'Mulgore'), (112, b'Orneval'), (113, b'Reflet-de-Lune'), (114, b'Silithus'), (115, b'Sombrivage'), (116, b'Tanaris'), (117, b'Tarides du Nord'), (118, b'Tarides du Sud'), (119, b'Teldrassil'), (120, b'Uldum'), (121, b"\xc3\x8eles de l'\xc3\x89cho")]), (b'Norfendre', [(200, b'Bassin de Sholazar'), (201, b'D\xc3\xa9solation des dragons'), (202, b'Fjord Hurlant'), (203, b'For\xc3\xaat du Chant de cristal'), (204, b"Joug-d'hiver"), (205, b'La Couronne de glace'), (206, b'Les Grisonnes'), (207, b'Les pics Foudroy\xc3\xa9s'), (208, b'Toundra Bor\xc3\xa9enne'), (209, b"Zul'Drak")]), (b'Pandarie', [(300, b'D\xc3\xa9sert de Tanlong'), (301, b'Etendues sauvages de Krasarang'), (302, b'La for\xc3\xaat de Jade'), (303, b'Sommet de Kun-Lai'), (304, b"Terres de l'Angoisse"), (305, b"Val de l'Eternel Printemps"), (306, b'Vall\xc3\xa9e des Quatre vents')]), (b'Iles bris\xc3\xa9es', [(400, b'Azsuna'), (401, b'Haut-Roc'), (402, b'Suramar'), (403, b'Tornheim'), (404, b"Val'Sharah")]), (b'Kezan', [(500, b'Kezan')]), (b'Zandalar', [(600, b'Zandalar')])], default=23, null=True),
        ),
        migrations.AlterField(
            model_name='objet',
            name='qualite',
            field=models.CharField(choices=[(b'm', b'M\xc3\xa9diocre'), (b'c', b'Commun'), (b'i', b'Inhabituel'), (b'r', b'Rare'), (b'e', b'Epique'), (b'l', b'L\xc3\xa9gendaire'), (b'u', b'Unique')], default=b'Commun', max_length=1),
        ),
        migrations.AlterField(
            model_name='quete',
            name='difficulte',
            field=models.SmallIntegerField(choices=[(1, b'Facile'), (2, b'Moyenne'), (3, b'Difficile'), (4, b'Tr\xc3\xa8s difficile'), (5, b'Suicidaire'), (6, b'Inconnue')], default=2),
        ),
        migrations.AlterField(
            model_name='quete',
            name='etat',
            field=models.SmallIntegerField(choices=[(1, b'En attente'), (2, b'R\xc3\xa9serv\xc3\xa9e'), (3, b'Accomplie')], default=1),
        ),
        migrations.AlterField(
            model_name='quete',
            name='zone',
            field=models.SmallIntegerField(choices=[(b"Royaumes de l'est", [(0, b'Bois de la P\xc3\xa9nombre'), (1, b'Bois des Chants \xc3\xa9ternels'), (2, b'Cap Strangleronce'), (3, b'Clairi\xc3\xa8res de Tirisfal'), (4, b'Contreforts de Hautebrande'), (5, b'Dun Morogh'), (6, b'D\xc3\xa9fil\xc3\xa9 de Deuillevent'), (7, b"For\xc3\xaat d'Elwynn"), (8, b'For\xc3\xaat des Pins-Argent\xc3\xa9s'), (9, b'Giln\xc3\xa9as'), (10, b'Gorge des Vents br\xc3\xbblants'), (11, b'Hautes-terres Arathies'), (12, b'Hautes-terres du Cr\xc3\xa9puscule'), (13, b"Kul'Tiras"), (14, b'Les Carmines'), (15, b'Les Hinterlands'), (16, b'Les Paluns'), (17, b'Les terres Fant\xc3\xb4mes'), (18, b'Loch Modan'), (19, b"Maleterres de l'Est"), (20, b"Maleterres de l'Ouest"), (21, b'Marais des Chagrins'), (22, b"Marche de l'Ouest"), (23, b'Noirebois'), (24, b'Steppes Ardentes'), (25, b'Strangleronce septentrionale'), (26, b'Terres Foudroy\xc3\xa9es'), (27, b'Terres Ingrates'), (28, b"\xc3\x8ele de Quel'Danas")]), (b'Kalimdor', [(100, b'Azshara'), (101, b"Berceau-de-l'Hiver"), (102, b"Crat\xc3\xa8re d'Un'Goro"), (103, b'Durotar'), (104, b'D\xc3\xa9solace'), (105, b'F\xc3\xa9ralas'), (106, b'Gangrebois'), (107, b'Les Serres-Rocheuses'), (108, b"Mar\xc3\xa9cage d'\xc3\x82prefange"), (109, b'Mille pointes'), (110, b'Mont Hyjal'), (111, b'Mulgore'), (112, b'Orneval'), (113, b'Reflet-de-Lune'), (114, b'Silithus'), (115, b'Sombrivage'), (116, b'Tanaris'), (117, b'Tarides du Nord'), (118, b'Tarides du Sud'), (119, b'Teldrassil'), (120, b'Uldum'), (121, b"\xc3\x8eles de l'\xc3\x89cho")]), (b'Norfendre', [(200, b'Bassin de Sholazar'), (201, b'D\xc3\xa9solation des dragons'), (202, b'Fjord Hurlant'), (203, b'For\xc3\xaat du Chant de cristal'), (204, b"Joug-d'hiver"), (205, b'La Couronne de glace'), (206, b'Les Grisonnes'), (207, b'Les pics Foudroy\xc3\xa9s'), (208, b'Toundra Bor\xc3\xa9enne'), (209, b"Zul'Drak")]), (b'Pandarie', [(300, b'D\xc3\xa9sert de Tanlong'), (301, b'Etendues sauvages de Krasarang'), (302, b'La for\xc3\xaat de Jade'), (303, b'Sommet de Kun-Lai'), (304, b"Terres de l'Angoisse"), (305, b"Val de l'Eternel Printemps"), (306, b'Vall\xc3\xa9e des Quatre vents')]), (b'Iles bris\xc3\xa9es', [(400, b'Azsuna'), (401, b'Haut-Roc'), (402, b'Suramar'), (403, b'Tornheim'), (404, b"Val'Sharah")]), (b'Kezan', [(500, b'Kezan')]), (b'Zandalar', [(600, b'Zandalar')])], default=23, null=True),
        ),
    ]
