# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0032_auto_20170519_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nom',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prenom',
            field=models.CharField(default=b'', max_length=30),
        ),
    ]
