# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0032_auto_20170723_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbaletrier',
            name='as_du_tir',
        ),
        migrations.RemoveField(
            model_name='arbaletrier',
            name='maitr_arba',
        ),
        migrations.RemoveField(
            model_name='arbaletrier',
            name='visee_prec',
        ),
    ]
