# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0033_auto_20170724_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorcier',
            name='bouclier_feu',
        ),
        migrations.RemoveField(
            model_name='sorcier',
            name='bouclier_mana',
        ),
        migrations.RemoveField(
            model_name='sorcier',
            name='grand_sorcier',
        ),
    ]
