# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0033_auto_20170519_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiche',
            options={'ordering': ['nom', 'prenom'], 'permissions': (('plus_de_15_fiches', 'Peut faire plus de quinze fiches'),), 'verbose_name': 'fiche', 'verbose_name_plural': 'fiches'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='prenom',
        ),
        migrations.AddField(
            model_name='fiche',
            name='creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
