# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0034_auto_20170524_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiche',
            old_name='medaille',
            new_name='medailles',
        ),
    ]
