# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0034_auto_20170724_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='avant_garde',
            name='pv_max',
            field=models.SmallIntegerField(default=11),
        ),
    ]
