# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0035_auto_20170524_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='sexe',
            field=models.CharField(choices=[(b'h', b'Homme'), (b'f', b'Femme')], default=b'Homme', max_length=1),
        ),
    ]
