# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0036_auto_20170525_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='ville_de_naissance',
            field=models.CharField(default=b'Inconnue', max_length=50),
        ),
    ]
