# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fiches.models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0038_auto_20170526_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effet', models.CharField(default=b'Aucun', max_length=100)),
                ('autres_effets', models.CharField(default=b'Aucun', max_length=100)),
                ('effet_ig', models.CharField(default=b'Aucun', max_length=100)),
                ('force', fiches.models.IntegerRangeField(default=b'0')),
                ('intell', fiches.models.IntegerRangeField(default=b'0')),
                ('agi', fiches.models.IntegerRangeField(default=b'0')),
                ('membre', models.SmallIntegerField(choices=[(b'1', b'Main principale'), (b'2', b'Autre main'), (b'3', b'T\xc3\xaate'), (b'4', b'Epaules'), (b'5', b'Torse'), (b'6', b'Mains'), (b'7', b'Taille'), (b'8', b'Jambes'), (b'9', b'Pieds'), (b'10', b'Dos'), (b'11', b'Cou'), (b'12', b'Index gauche'), (b'13', b'Majeur gauche'), (b'14', b'Annulaire gauche'), (b'15', b'Auriculaire gauche'), (b'16', b'Index droit'), (b'17', b'Majeur droit'), (b'18', b'Annulaire droit'), (b'19', b'Auriculaire droit'), (b'20', b'Divers')], default=b'5')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objets', models.ManyToManyField(related_name='equipement', to='fiches.Armure')),
            ],
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases', models.ManyToManyField(related_name='inventaire', to='fiches.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=b'Aucun', max_length=75)),
                ('qualite', models.CharField(choices=[(b'm', b'M\xc3\xa9diocre'), (b'c', b'Commun'), (b'i', b'Inhabituel'), (b'r', b'Rare'), (b'e', b'Epique'), (b'l', b'L\xc3\xa9gendaire'), (b'u', b'Unique')], default=b'Commun', max_length=1)),
                ('description', models.CharField(default=b'Aucun', max_length=200)),
                ('prix', models.IntegerField(default=b'0')),
                ('poids', models.IntegerField(default=b'0')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='objet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='fiches.Objet'),
        ),
        migrations.AddField(
            model_name='armure',
            name='objet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armure', to='fiches.Objet'),
        ),
    ]
