# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0039_auto_20170602_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armure',
            name='membre',
            field=models.SmallIntegerField(choices=[(1, b'Main principale'), (2, b'Autre main'), (3, b'T\xc3\xaate'), (4, b'Epaules'), (5, b'Torse'), (6, b'Mains'), (7, b'Taille'), (8, b'Jambes'), (9, b'Pieds'), (10, b'Dos'), (11, b'Cou'), (12, b'Index gauche'), (13, b'Majeur gauche'), (14, b'Annulaire gauche'), (15, b'Auriculaire gauche'), (16, b'Index droit'), (17, b'Majeur droit'), (18, b'Annulaire droit'), (19, b'Auriculaire droit'), (20, b'Divers')], default=b'5'),
        ),
    ]
