# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import fiches.models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0040_auto_20170602_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armure',
            options={'ordering': ['membre'], 'permissions': (('armure_ok', 'Peut faire des armures'),), 'verbose_name': 'armure', 'verbose_name_plural': 'armures'},
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['nombre', 'objet'], 'permissions': (('case_ok', 'Peut faire des cases'),), 'verbose_name': 'case', 'verbose_name_plural': 'cases'},
        ),
        migrations.AlterModelOptions(
            name='equipement',
            options={'permissions': (('equipement_ok', 'Peut faire des \xe9quipements'),), 'verbose_name': 'equipement', 'verbose_name_plural': 'equipements'},
        ),
        migrations.AlterModelOptions(
            name='inventaire',
            options={'permissions': (('inventaire_ok', 'Peut faire des inventaires'),), 'verbose_name': 'inventaire', 'verbose_name_plural': 'inventaires'},
        ),
        migrations.AlterModelOptions(
            name='objet',
            options={'ordering': ['nom'], 'permissions': (('objet_ok', 'Peut faire des objets'),), 'verbose_name': 'objet', 'verbose_name_plural': 'objets'},
        ),
        migrations.AddField(
            model_name='case',
            name='nombre',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='armure',
            name='agi',
            field=fiches.models.IntegerRangeField(default=0),
        ),
        migrations.AlterField(
            model_name='armure',
            name='force',
            field=fiches.models.IntegerRangeField(default=0),
        ),
        migrations.AlterField(
            model_name='armure',
            name='intell',
            field=fiches.models.IntegerRangeField(default=0),
        ),
        migrations.AlterField(
            model_name='armure',
            name='membre',
            field=models.SmallIntegerField(choices=[(1, b'Main principale'), (2, b'Autre main'), (3, b'T\xc3\xaate'), (4, b'Epaules'), (5, b'Torse'), (6, b'Mains'), (7, b'Taille'), (8, b'Jambes'), (9, b'Pieds'), (10, b'Dos'), (11, b'Cou'), (12, b'Index gauche'), (13, b'Majeur gauche'), (14, b'Annulaire gauche'), (15, b'Auriculaire gauche'), (16, b'Index droit'), (17, b'Majeur droit'), (18, b'Annulaire droit'), (19, b'Auriculaire droit'), (20, b'Divers')], default=5),
        ),
        migrations.AlterField(
            model_name='objet',
            name='poids',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='objet',
            name='prix',
            field=models.IntegerField(default=0),
        ),
    ]
