# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0041_auto_20170603_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet',
            name='image',
            field=models.ImageField(default=b'images/site/WoWUnknownItem01.PNG', upload_to=b'images/users'),
        ),
    ]
