# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0042_objet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='armure',
            name='armure',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipement',
            name='nom',
            field=models.CharField(default=b'Inventaire', max_length=50),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='nom',
            field=models.CharField(default=b'Inventaire', max_length=50),
        ),
        migrations.AlterField(
            model_name='armure',
            name='membre',
            field=models.SmallIntegerField(choices=[(1, b'Main principale'), (2, b'Autre main'), (3, b'T\xc3\xaate'), (4, b'Epaules'), (5, b'Torse'), (6, b'Mains'), (7, b'Taille'), (8, b'Jambes'), (9, b'Pieds'), (10, b'Dos'), (11, b'Cou'), (12, b'Doigt'), (13, b'Poignets'), (14, b'Divers')], default=5),
        ),
    ]
