# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0043_auto_20170606_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='equipement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proprietaire', to='fiches.Equipement'),
        ),
        migrations.AddField(
            model_name='fiche',
            name='inventaire_fdg',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proprietaire', to='fiches.Inventaire'),
        ),
        migrations.AddField(
            model_name='fiche',
            name='main_dir',
            field=models.CharField(choices=[(b'g', b'Gauche'), (b'd', b'Droite')], default=b'Droite', max_length=1),
        ),
    ]
