# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0044_auto_20170606_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='equipement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proprietaire', to='fiches.Equipement'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='inventaire_fdg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proprietaire', to='fiches.Inventaire'),
        ),
    ]
