# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0045_auto_20170606_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='nom',
            field=models.CharField(default=b'Equipement', max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='inventaire',
            field=models.CharField(blank=True, default=b'A venir', max_length=6000, null=True),
        ),
    ]
