# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fiches.models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0046_auto_20170607_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe_ag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=b'Fantassin', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rpg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=b'Classique', max_length=50)),
            ],
            options={
                'permissions': (('plusieurs_rpgs', "Participe \xe0 d'autres campagnes"),),
                'verbose_name': 'rpg',
                'verbose_name_plural': 'rpgs',
                'default_related_name': 'rpg',
            },
        ),
        migrations.AlterField(
            model_name='objet',
            name='description',
            field=models.CharField(default=b'Aucune', max_length=500),
        ),
        migrations.AlterField(
            model_name='objet',
            name='nom',
            field=models.CharField(max_length=75),
        ),
        migrations.CreateModel(
            name='Apothicaire',
            fields=[
                ('classe_ag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fiches.Classe_ag')),
                ('medecine', fiches.models.IntegerRangeField(default=0)),
                ('chirurgie', fiches.models.IntegerRangeField(default=0)),
                ('poison', fiches.models.IntegerRangeField(default=0)),
                ('guerisseur', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
                ('alchimie', fiches.models.IntegerRangeField(default=0)),
                ('equitation', fiches.models.IntegerRangeField(default=0)),
                ('maitr_scalpel', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
                ('lancer_fioles', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
                ('maitr_guerisseur', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
                ('enfumeur', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
            ],
            bases=('fiches.classe_ag',),
        ),
        migrations.CreateModel(
            name='Avant_garde',
            fields=[
                ('rpg_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fiches.Rpg')),
                ('race_rpg', models.CharField(choices=[(b'n', b'Nain'), (b'e', b'Haut-elfe'), (b'h', b'Humain')], default=b'Humain', max_length=1)),
                ('ex_prof', models.SmallIntegerField(choices=[(1, b'Forgeron'), (2, b'Chasseur'), (3, b'Cuisinier'), (4, b'Tavernier'), (5, b"Facteur d'arc"), (6, b'Tanneur'), (7, b'Architecte'), (8, b'Eb\xc3\xa9niste'), (9, b'Autre m\xc3\xa9tier')], default=9)),
                ('cap_combat', fiches.models.IntegerRangeField(default=1)),
                ('cap_tir', fiches.models.IntegerRangeField(default=1)),
                ('force', fiches.models.IntegerRangeField(default=1)),
                ('endu', fiches.models.IntegerRangeField(default=1)),
                ('perce', fiches.models.IntegerRangeField(default=1)),
                ('agi', fiches.models.IntegerRangeField(default=1)),
                ('intell', fiches.models.IntegerRangeField(default=1)),
                ('charisme', fiches.models.IntegerRangeField(default=1)),
                ('force_men', fiches.models.IntegerRangeField(default=1)),
                ('pv', models.SmallIntegerField(default=11)),
                ('ps', models.SmallIntegerField(default=0)),
                ('pf', models.SmallIntegerField(default=0)),
                ('niveau', models.SmallIntegerField(default=1)),
                ('xp', models.SmallIntegerField(default=0)),
                ('blessures', models.CharField(blank=True, default=b'Sans', max_length=800, null=True)),
                ('troubles_ment', models.CharField(blank=True, default=b'Sans', max_length=800, null=True)),
            ],
            bases=('fiches.rpg',),
        ),
        migrations.CreateModel(
            name='Fantassin',
            fields=[
                ('classe_ag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fiches.Classe_ag')),
                ('intim', fiches.models.IntegerRangeField(default=0)),
                ('parer_fleches', fiches.models.IntegerRangeField(default=0)),
                ('athle', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
                ('resistant', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
                ('cc', fiches.models.IntegerRangeField(default=0)),
                ('prot', fiches.models.IntegerRangeField(default=0)),
                ('epeiste', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
                ('crane_dur', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
                ('equitation', fiches.models.IntegerRangeField(default=0)),
                ('maitr_glaive', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
                ('maitr_arm_lourde', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
                ('feroce', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
                ('implacable', models.BooleanField(choices=[(True, b'Oui'), (False, b'Non')], default=False)),
            ],
            bases=('fiches.classe_ag',),
        ),
        migrations.AddField(
            model_name='fiche',
            name='rpg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to='fiches.Rpg'),
        ),
        migrations.AddField(
            model_name='avant_garde',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiches.Classe_ag'),
        ),
    ]
