# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 18:42
from __future__ import unicode_literals

from django.db import migrations
import fiches.models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0047_auto_20170620_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='nombre',
            field=fiches.models.IntegerRangeField(default=1),
        ),
    ]
